services:
  app:
    profiles: ["containerized"]
    build:
      context: .
    environment:
      APP_STORAGE_UPLOAD_DIR: /app/uploads
    ports:
      - "8080:8080"
    volumes:
      - synxo_data:/app/data
      - synxo_uploads:/app/uploads

volumes:
  synxo_data:
  synxo_uploads:
