spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/synxo?ssl=false&sslmode=disable
spring.datasource.username=synxo
spring.datasource.password=synxo
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
app.storage.upload-dir=./uploads
